### ISSUE TITLE
Concurrent server backend

### ISSUE THREAD

**Issue by roberth** [roberth/uu-cs-orc#2]

**Comment by RKuipers** [comment]
Er is nu 1 server thread, die wacht op nieuwe inkomende connecties, die ieder hun eigen thread krijgen.

Je kunt dit doen door de server op te starten (die dan zegt op welke port hij luistert) en dan clients te starten met bijv. telnet. In die client kun je record-notation commands geven (zoals bij sequentiele implementatie) en daarmee de server state aanpassen en opvragen.

**Comment by roberth** [comment]
:+1:
